name: Run tests
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: 
      image: stelar7/advent-of-code-runner:2022
      volumes:
        - "${{ github.workspace }}:/test"

    steps:
      - name: Run tests
        shell: bash
        run: |
          cd /test;
          make test YEAR=2022 DAY=1;
          make test YEAR=2022 DAY=2;
          make test YEAR=2022 DAY=3;
          make test YEAR=2022 DAY=4;
          make test YEAR=2022 DAY=5;
          make test YEAR=2022 DAY=6;
          make test YEAR=2022 DAY=7;
          make test YEAR=2022 DAY=8;
          make test YEAR=2022 DAY=9;
          make test YEAR=2022 DAY=10;
          make test YEAR=2022 DAY=11;
          make test YEAR=2022 DAY=12;
          make test YEAR=2022 DAY=13;
          make test YEAR=2022 DAY=14;
          make test YEAR=2022 DAY=15;
          make test YEAR=2022 DAY=16;
          make test YEAR=2022 DAY=17;
          make test YEAR=2022 DAY=18;
          make test YEAR=2022 DAY=19;
          make test YEAR=2022 DAY=20;
          make test YEAR=2022 DAY=21;
          make test YEAR=2022 DAY=22;
          make test YEAR=2022 DAY=23;
          make test YEAR=2022 DAY=24;
          make test YEAR=2022 DAY=25;

      - name: Check for failed tests
        run: |
          ! grep -r "❌" leaderboards/*
          exit $?

      - name: Push new leaderboards
        if: always() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com";
          git config --local user.name "github-actions[bot]";
          git add leaderboards/*
          git commit -m "Update leaderboards"
          git push
