name: Run tests
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install NodeJS@18
        uses: actions/setup-node@v2
        with: 
          node-version: 18

      - name: Install essentials
        run: |
          sudo apt-get update;
          sudo apt-get install -yqq --no-install-recommends build-essential git wget ca-certificates curl unzip ninja-build ccache gnupg apt-transport-https;
          
      - name: Install cmake
        run: |
          sudo apt remove --purge --auto-remove cmake; 
          sudo apt update; 
          sudo apt install -y software-properties-common lsb-release; 
          sudo apt clean all; 
          sudo wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null; 
          sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"; 
          sudo apt update; 
          sudo apt install cmake -yqq;
      
      - name: Install Mono and .NET (C#)
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF;
          echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list;
          wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          rm packages-microsoft-prod.deb
          sudo apt update;
          sudo apt install mono-complete dotnet-sdk-6.0 -yqq;

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      
      - name: Elixir setup
        uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          elixir-version: '1.14.0'
          otp-version: '25.1.0'


      - name: Install other compilers
        run: |
          sudo apt-get update;
          sudo apt-get install -yqq --no-install-recommends openjdk-17-jdk golang perl nodejs php-cli python3 ruby;
          sudo rm -rf /var/lib/apt/lists/*;
          sudo apt-get autoremove -yqq;

      - name: Install 05AB1E
        run: |
          git clone https://github.com/Adriandmen/05AB1E.git;
          cd 05AB1E;
          (yes | PATH=/usr/bin:$PATH mix local.hex --force);
          PATH=/usr/bin:$PATH mix deps.get;
          (yes | PATH=/usr/bin:$PATH MIX_ENV=prod mix escript.build);
          mv osabie /usr/local/bin/osabie;

      - name: Print versions
        run: |
          uname -a
          bash --version
          cargo --version
          cmake --version
          dotnet --version
          gcc --version
          go version
          java --version
          mono --version=number
          node --version
          python3 --version
          rustc --version
          ruby --version
          erlang --version
          elixir --version

      - name: Run tests
        run: |
          make test YEAR=2022 DAY=1;
          make test YEAR=2022 DAY=2;
          make test YEAR=2022 DAY=3;
          make test YEAR=2022 DAY=4;
          make test YEAR=2022 DAY=5;
          make test YEAR=2022 DAY=6;
          make test YEAR=2022 DAY=7;
          make test YEAR=2022 DAY=8;
          make test YEAR=2022 DAY=9;
          make test YEAR=2022 DAY=10;
          make test YEAR=2022 DAY=11;
          make test YEAR=2022 DAY=12;
          make test YEAR=2022 DAY=13;
          make test YEAR=2022 DAY=14;
          make test YEAR=2022 DAY=15;
          make test YEAR=2022 DAY=16;
          make test YEAR=2022 DAY=17;
          make test YEAR=2022 DAY=18;
          make test YEAR=2022 DAY=19;
          make test YEAR=2022 DAY=20;
          make test YEAR=2022 DAY=21;
          make test YEAR=2022 DAY=22;
          make test YEAR=2022 DAY=23;
          make test YEAR=2022 DAY=24;
          make test YEAR=2022 DAY=25;

      - name: Check for failed tests
        run: |
          ! grep -r "❌" leaderboards/*
          exit $?

      - name: Push new leaderboards
        if: always() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com";
          git config --local user.name "github-actions[bot]";
          git add leaderboards/*
          git commit -m "Update leaderboards"
          git push
